### ISSUE TITLE
AdaptiveCards API Handling

### ISSUE THREAD

**Issue by fbellom** [WebexCommunity/WebexPythonSDK#134]
Hi,

I'd like to have the ability to create an AdaptiveCard Object, and during the creation process to validate if there is an existing Webhook supporting the "attachmentAction", if not then create one using the same Target as the "messages" Webhook, to accelerate the adoption and testing of this feature.

Flow
Create AdaptiveCard Object
 - Validate if a Webhook for "attachmentAction" exists
 - If not, create a new WH and use the message WH Target Property

**Comment by sQu4rks** [comment]
Hi @fbellom 

thanks for opening this issue. Just to verify, would you want a code sample on how to accomplish such a workflow using the webexteamssdk or are you looking for this workflow to be natively included in the webexteamssdk?

**Comment by cmlccie** [comment]
Closing feature request; this issue is over four years old and appears to be asking for what may be bespoke higher-level functionality to be added to the SDK, which if enabled by default, would creating surprising functionality for most users. If we implemented this, it would likely have to be disabled by default and enabled with a flag.

Adding a webhook should be straightforward for an SDK user.
